[[pages]]
name = "Setup"
icon = "âš™ï¸"
is_section = true

[[pages]]
name = "Company Initialization and Setup"
icon = "ğŸ¢"
path = "pages/initialization_page.py"

[[pages]]
name = "Monitoring and Analysis"
icon = "ğŸ“ˆ"
is_section = true

[[pages]]
name = "Real-Time Monitoring"
icon = "ğŸ”"
path = "pages/monitoring_page.py"

[[pages]]
name = "Sentiment and Predictive Analysis"
icon = "ğŸ“Š"
path = "pages/analysis_page.py"

[[pages]]
name = "Validation and Reporting"
icon = "âœ…"
is_section = true

[[pages]]
name = "Data Validation"
icon = "ğŸ“‚"
path = "pages/data_validation_page.py"

[[pages]]
name = "Reporting"
icon = "ğŸ“‘"
path = "pages/reporting_page.py"

[[pages]]
name = "Alerts and Analysis"
icon = "ğŸš¨"
is_section = true

[[pages]]
name = "Emergency Alerts"
icon = "ğŸš¨"
path = "pages/alerts_page.py"

[[pages]]
name = "Chat with Bot"
icon = "ğŸ’¬"
is_section = true

[[pages]]
name = "Start Chat"
icon = "ğŸ¤–"
path = "pages/chat_bot_with_search_online.py"

[[pages]]
name = "Influencer and Competitor Analysis"
icon = "ğŸ‘¥"
path = "pages/influencer_analysis_page.py"