# pages.toml
[[pages]]
name = "Initialization and Setup"
icon = "âš™ï¸"
path = "pages/initialization_page.py"

[[pages]]
name = "Real-Time Monitoring and Data Collection"
icon = "ğŸ“ˆ"
path = "pages/monitoring_page.py"

[[pages]]
name = "Sentiment and Predictive Analysis"
icon = "ğŸ“Š"
path = "pages/analysis_page.py"

[[pages]]
name = "Data Validation and Selection"
icon = "âœ…"
path = "pages/data_validation_page.py"

[[pages]]
name = "Reporting and Analysis"
icon = "ğŸ“‘"
path = "pages/reporting_page.py"

[[pages]]
name = "Emergency Response and Alerts"
icon = "ğŸš¨"
path = "pages/alerts_page.py"

[[pages]]
name = "Start Chat"
icon = "ğŸ¤–"
path = "pages/chat_bot_with_search_online.py"

[[pages]]
name = "Influencer and Competitor Analysis"
icon = "ğŸ‘¥"
path = "pages/influencer_analysis_page.py"
